name: CI

on:
  push:
    branches: [ master, fix/**, feature/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Enforce max file size
        run: |
          # Fail if any repo file exceeds 98MB (102,760,448 bytes)
          max=102760448
          while IFS= read -r -d '' f; do
            sz=$(stat -c%s "$f")
            if [ "$sz" -ge "$max" ]; then
              echo "File too large: $f ($sz bytes)"
              exit 1
            fi
          done < <(git ls-files -z)
      - name: Run tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          pytest -q
