name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build release artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm, macos-13, macos-14, ubuntu-latest, ubuntu-22.04-arm]
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install PyQt6; fi
          pip install pyinstaller requests ffmpeg-python

      - name: Install Linux extras (patchelf)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y patchelf
          fi

      - name: Build PyQt6 app
        shell: bash
        run: |
          pyinstaller --name WINFF-GUI-PyQt6 --noconfirm --onefile --windowed GUI_pyqt6_WINFF.py

      - name: Build Tkinter app
        shell: bash
        run: |
          pyinstaller --name WINFF-GUI-Tkinter --noconfirm --onefile --windowed GUI_tkinter_WINFF.py

      - name: Package artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          arch_lc=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp dist/WINFF-GUI-PyQt6.exe "artifacts/WINFF-GUI-PyQt6-win-${arch_lc}.exe"
            cp dist/WINFF-GUI-Tkinter.exe "artifacts/WINFF-GUI-Tkinter-win-${arch_lc}.exe"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            cd dist
            zip -r "../artifacts/WINFF-GUI-PyQt6-macos-${arch_lc}.app.zip" "WINFF-GUI-PyQt6.app"
            zip -r "../artifacts/WINFF-GUI-Tkinter-macos-${arch_lc}.app.zip" "WINFF-GUI-Tkinter.app"
            cd -
          else
            cp dist/WINFF-GUI-PyQt6 "artifacts/WINFF-GUI-PyQt6-linux-${arch_lc}"
            cp dist/WINFF-GUI-Tkinter "artifacts/WINFF-GUI-Tkinter-linux-${arch_lc}"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}-release-artifacts
          path: artifacts/*

  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*-release-artifacts"
          merge-multiple: true
          path: release-assets

      - name: Show assets
        run: ls -la release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
